name: pg_duckdb_analytics
version: "1.0.0"
profile: pg_duckdb_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

on-run-start:
  - "SET duckdb.force_execution = true"

models:
  pg_duckdb_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
