repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff lint
        language: system
        entry: uv run sqlfluff lint
        types: [sql]
        pass_filenames: true
